# -*- coding: utf-8 -*-
"""Quadratic formula.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L3XdxhXK8Qh93AUfs1y5NmWE72POa8yd
"""

print("welcome to the Quadtradic formula machine! Plase enter in the vales for a,b,and c, so we can find the two values for X")
aval=int(input("a value: "))
bval=int(input("b value: "))
cval=int(input("c value: "))
print(" ")
import math

negb=-bval

sqredval=(bval*bval)-(4*aval*cval)
sqrt = (math.pow(sqredval, 0.5)) 

bottom=2*aval 

firstan=(negb+sqrt)/bottom
sedcoundan=(negb-sqrt)/bottom 

print("Your first answer is: ", firstan)
print("Your secound anwser is: ", sedcoundan)

print("Dont forget to either plug both the answers in or factor the eqaution")